[build]
  publish = "dist"
  command = "npm run build"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*.glb"
  [headers.values]
    Content-Type = "model/gltf-binary"

[[headers]]
  for = "/*.wasm"
  [headers.values]
    Content-Type = "application/wasm"
